version: '3.9'

services:

  postgres:
    env_file: .env
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  flask_web:
    env_file: .env
    networks:
      - backend
    build: .
    ports:
       - 0.0.0.0:5000:5000
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: bridge
