version: '3.11'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_DB: 'nimble_db'
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
